services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.docker
    restart: unless-stopped
    develop:
      watch:
        - path: ./backend
          action: rebuild
    command: ["npm", "run", "start:ts"]

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: accounts-app-db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/initdb:/docker-entrypoint-initdb.d:ro
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:80"
    restart: unless-stopped
    develop:
      watch:
        - path: ./frontend
          action: rebuild

volumes:
  db-data: