services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - internal
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env.docker
    restart: unless-stopped
    develop:
      watch:
        - path: ./backend
          action: rebuild
    command: ["npm", "run", "start:ts"]

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recurring-worker
    env_file:
      - ./backend/.env.docker
    networks:
      - internal
    depends_on:
      - db
    restart: unless-stopped
    command: ["node", "dist/workers/workerDaemon.js"]

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: accounts-app-db
    ports:
      - "5432:5432"
    networks:
      - internal
    #ports:
    # - "5432:5432"
    volumes:
      - ./backend/initdb:/docker-entrypoint-initdb.d:ro
      - db-data:/var/lib/postgresql/data
      - ./backend/prisma/migrations:/app/prisma/migrations
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - internal
    develop:
      watch:
        - path: ./frontend
          action: rebuild

volumes:
  db-data:

networks:
  internal:
